# Generated by Django 3.2.5 on 2021-07-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, 'admin'), (2, 'superuser'), (3, 'user')], default=1),
        ),
    ]
